### ISSUE TITLE
feature request: sort mode

### ISSUE THREAD

**Issue by alexmyczko** [luspi/photoqt#10]
Hi

I was curious if you'd be interested to implement a sort by dominant/average color of image?

**Comment by luspi** [comment]
Good news: I had some free time over the weekend and implemented this in PhotoQt. Starting with the next release (v2.6), there will be an 'advanced sort' feature that allows you to sort a folder by dominant or average color, and also by image resolution. Since this can be rather slow, this has to be manually initiated after a folder has been opened and an image has been loaded. 

You will be able to find this feature in the main menu or you can call it via shortcut. When selecting the feature you're usually provided with some options to choose from (what criteria to use, etc.), but there is also an available shortcut to immediately do the sorting based on the last used settings.

**Comment by alexmyczko** [comment]
@luspi Thank you! I also have good news, Ubuntu 22.04 LTS will have photoqt: https://packages.ubuntu.com/search?keywords=photoqt

**Comment by luspi** [comment]
Oh, that's indeed great news, thanks for letting me know!
