### ISSUE TITLE
[Flatpak] Move-To-Trash not working

### ISSUE THREAD

**Issue by KAGEYAM4** [luspi/photoqt#24]
`KDE Application Platform         org.kde.Platform                  6.6                   system`

![image](https://github.com/luspi/photoqt/assets/75798544/020f80c0-6947-4714-8a31-1e79a8e37a21)

Permanently-Deleting works.

Is there a way i could help/provide in more debuggable information?

This action works perfectly for aur-package.

This is what i could find - https://github.com/flatpak/flatpak/issues/1253

**Comment by luspi** [comment]
Alright, I found a way to fix this behavior, though a little differently. It turns out that Gio supports trashing files from sandboxed apps properly, so [for now I'm using that for flatpak builds](https://github.com/luspi/photoqt/commit/d8eaeacf02616e3801bc56d8766d45f8227779c5). I'm planning on releasing the next version of PhotoQt this week, and this update will ship with that release.
