### ISSUE TITLE
Scrolling through images with the mouse wheel

### ISSUE THREAD

**Issue by KOT040188** [luspi/photoqt#6]
Previously, to scroll through images, you had to turn the mouse wheel by one click.  Now you need to make two clicks while scrolling the wheel to scroll to the next image.  I would like to bring back the old behavior. Photoqt 2.1.1

**Comment by luspi** [comment]
Hi @KOT040188 
You should be able to fix that in the settings manager:
Open Settings Manager and activate expert mode (button on the bottom left). In the first tab ('Interface') go down to "mouse wheel sensitivity" and make sure it is set all the way to the left (contrary to the text to the left of the slider, that is the most sensitive position).

Btw: Don't let the labels to the left/right of the slider confuse you, I just noticed that they are opposite of each other. That will be fixed in the next release.

**Comment by KOT040188** [comment]
> Hi @KOT040188
> You should be able to fix that in the settings manager:
> Open the settings manager and activate the expert mode (button on the bottom left). In the first tab ('Interface') go down to "mouse wheel sensitivity" and make sure it is set all the way to the left (contrary to the text to the left of the slider, that is the most sensitive position).
> 
> Btw: Don't let the labels to the left/right of the slider confuse you, I just noticed that they are opposite of each other. That will be fixed in the next release.

Thanks, it worked!
